version: "3.8"
services:
  postgres-db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bdmilkstgo
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
  app:
    container_name: proyectomingeso1
    image: hfaravenak/proyectomingeso1
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/bdmilkstgo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=postgres
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres-db